<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.8.2</Version>
    <AssemblyVersion>2.0.8.2</AssemblyVersion>
    <FileVersion>2.0.8.2</FileVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\*.html" />
    <EmbeddedResource Include="Configuration\*.js" />
    <EmbeddedResource Include="Configuration\guide\*.png" />
    <EmbeddedResource Include="thumb.png" />
    <Content Include="thumb.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Common" Version="4.9.1.90" />
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
